const products = [
  {
    id: 1,
    name: "bracelet",
    description: "Enhanced audio for your TV experience.",
    price: 129.99,
    images: "./public/bracelet1.jpg",
    category: "accessory",
    size: ["S", "M", "L"],
    stock: 60,
    quantity: 1,
  },

  {
    id: 2,
    name: "headwrap ",
    description: "Ergonomic design with customizable DPI settings.",
    price: 280,
    images: "./public/headwrap.jpg",
    category: "accessory",
    size: ["S", "M", "L"],
    stock: 90,
    quantity: 1,
  },
  {
    id: 3,
    name: "xibelani red",
    description: "",
    price: "3000",
    images: "/public/xib-red.jpg",
    category: "xibelani",
    size: ["S", "M", "L"],
    stock: 150,
    quantity: 1,
  },
  {
    id: 4,
    name: "xibelani black ",
    description: "Ergonomic design with customizable DPI settings.",
    price: 3100,
    images: "./public/pink-takkies.jpg",
    category: "shoes",
    size: ["S", "M", "L"],
    stock: 90,
    quantity: 1,
  },

  {
    id: 5,
    name: "xibelani  orange",
    description: "Durable and stylish case for your phone.",
    price: 3200,
    images: "./public/xib-orange.jpg",
    category: "xibelani",
    size: ["S", "M", "L"],
    stock: 200,
    quantity: 1,
  },
  {
    id: 6,
    name: " Nkateko st",
    description: "Sleek design with multiple card slots.",
    price: 34.99,
    images: "./public/rhandzu-set.jpg",
    category: "Set",
    size: ["S", "M", "L"],
    stock: 200,
    quantity: 1,
  },

  {
    id: 7,
    name: "headwrap  ",
    description: "Ergonomic design with customizable DPI settings.",
    price: 200,
    images: "./public/headwrap1.jpg",
    category: "accessory",
    size: ["S", "M", "L"],
    stock: 90,
    quantity: 1,
  },
  {
    id: 8,
    name: "xibelani White ",
    description: "Portable speaker with exceptional sound quality.",
    price: 3600,
    images: "./public/xib-white.jpg",
    category: "xibelani",
    size: ["S", "M", "L"],
    stock: 100,
    quantity: 1,
  },
  {
    id: 9,
    name: "xibelani ",
    description: "Brew your perfect cup of coffee every morning.",
    price: 2800,
    images: "./public/xib-green.jpg",
    category: "xibelani",
    size: ["S", "M", "L"],
    stock: 80,
    quantity: 1,
  },
  {
    id: 10,
    name: "headwrap  ",
    description: "Ergonomic design with customizable DPI settings.",
    price: 3100,
    images: "./public/headwrap2.jpg",
    category: "accessory",
    size: ["S", "M", "L"],
    stock: 90,
    quantity: 1,
  },
  {
    id: 11,
    name: "headwrap  ",
    description: "Ergonomic design with customizable DPI settings.",
    price: 3100,
    images: "./public/headwrap3.jpg",
    category: "accessory",
    size: ["S", "M", "L"],
    stock: 90,
    quantity: 1,
  },
  {
    id: 12,
    name: "headwrap   ",
    description: "Ergonomic design with customizable DPI settings.",
    price: 3100,
    images: "./public/headwrap4.jpg",
    category: "accessory",
    size: ["S", "M", "L"],
    stock: 90,
    quantity: 1,
  },

  {
    id: 13,
    name: "xibelani pink",
    description: "Adjustable brightness and color temperature.",
    price: 3000,
    images: "./public/xib-pink.JPG",
    category: "xibelani",
    size: ["S", "M", "L"],
    stock: 120,
    quantity: 1,
  },

  {
    id: 14,
    name: "xibelani black ",
    description: "Ergonomic design with customizable DPI settings.",
    price: 3100,
    images: "./public/whit-takkies.jpg",
    category: "shoes",
    size: ["S", "M", "L"],
    stock: 90,
    quantity: 1,
  },
  {
    id: 15,
    name: "Makoti set",
    description: "Monitor your heart rate and activity levels.",
    price: 500,
    images: "./public/purple-set.jpg",
    category: "Set",
    size: ["S", "M", "L"],
    stock: 70,
    quantity: 1,
  },
  {
    id: 16,
    name: "khensani set",
    description: "Non-slip surface for all your workout needs.",
    price: 300,
    images: "./public/red-set.jpg",
    category: "Set",
    size: ["S", "M", "L"],
    stock: 150,
    quantity: 1,
  },
  {
    id: 17,
    name: "vumbhuri set",
    description: "",
    price: 500,
    images: "./public/red-set (2).jpg",
    category: "Set",
    size: ["S", "M", "L"],
    stock: 100,
    quantity: 1,
  },

  {
    id: 18,
    name: "xibelani black ",
    description: "Ergonomic design with customizable DPI settings.",
    price: 3100,
    images: "./public/xib-black.jpg",
    category: "xibelani",
    size: ["S", "M", "L"],
    stock: 90,
    quantity: 1,
  },
  {
    id: 19,
    name: "xibelani blue ",
    description: "Ergonomic design with customizable DPI settings.",
    price: 1000,
    images: "./public/xib.jpg",
    category: "xibelani",
    size: ["S", "M", "L"],
    stock: 90,
    quantity: 1,
  },
  {
    id: 20,
    name: " bracelet",
    description: "Sleek design with multiple card slots.",
    price: 34.99,
    images: "./public/bracelet.jpg",
    category: "accessory",
    size: ["S", "M", "L"],
    stock: 200,
    quantity: 1,
  },
  {
    id: 21,
    name: " xibelani Blue",
    description: "Sleek design with multiple card slots.",
    price: 34.99,
    images: "./public/xib-blue.jpg",
    category: "xibelani",
    size: ["S", "M", "L"],
    stock: 200,
    quantity: 1,
  },
];
export default products;
